# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development: &development
  secret_key_base: 81e9d1e5db64900041f0564cde8ee55f5a299cdd957d004bdf0b7c6444af2e9e6e76f3b993a1c20415391ee6d030d3d7ce499e74a7f27114d129ce43cc0cc5cb

development_local:
  <<: *development
  secret_key_base: b8d0a7ac013466c06da1073024f7285d6abe3747a25a60d00d82387918d612e9143e6ca7b5dc21446570e15946a3d60b56a7901dcac0e19c1753ee2e0726d078

development_remote:
  <<: *development
  secret_key_base: dec437bfa7e69a9ba4ad88838c9614986708be9384605d864058b74975399e5b965b3fd3fb6c88efe0f7869c1677cdbfa7be230f6e946a4e3c6ba2f24fb49272

staging: &staging
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging_local:
  <<: *staging
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
staging_remote:
  <<: *staging
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: ed8c5c0e784490891d1acd9e7ae4963d410bccf7f07e79c28dee1d50ca474828fb2dc8f7c7aa8d3a6ce619d0065e696f2abbd75a54dafbc13926cce8f7a6f361

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
