source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# secrets
gem 'figaro'

group :development, :development_local, :development_remote, :test do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Testing framework
  gem 'rspec-rails', '~> 3.7'
  # Test support for ActionCable
  gem 'action-cable-testing', '~> 0.3.0'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development, :development_local, :development_remote do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo'
gem 'tzinfo-data'

# Language Internazionalization
gem 'rails-i18n'

# Serializers let me choose how the output will be formatted
gem 'active_model_serializers', '~> 0.10.0'

# Devise token auth to manage token-based authentication
gem 'devise_token_auth', '~> 0.1.42'
gem 'omniauth', '>= 1.7.0'

# To manage cross-origin requests
gem 'rack-cors', :require => 'rack/cors'

# Required for delayed jobs
gem 'sidekiq',  '~>4.0'

# Kaminari handles pagination
gem 'kaminari', '~> 1.1.1'

# Kaminari modifier for API headers
gem 'api-pagination'

# To handle users authorizations
gem 'cancancan', '~> 2.0'

# This is to create fake data
gem 'ffaker', '~> 2.7.0'

# To grant code quality
gem 'rubocop', '~> 0.51'

# File Upload 
gem 'carrierwave', '~> 1.3.2'
# Automatic thumbnail for videos
gem 'carrierwave-video-thumbnailer', '~> 0.1.4'

# File upload for staging/production
gem 'fog', '~> 1.42.0'
gem "fog-aws"

# Files upload for base64 files
gem 'carrierwave-base64'

# Upload directly to S3 
gem 'carrierwave_direct', '~> 2.0.0'

# To edit images
gem 'mini_magick', '~> 4.8.0'

# To use soft-delete
gem "paranoia", "~> 2.3.1"

# Prevent Errno::ENOMEM with minimagick
gem 'posix-spawn', '~> 0.3.13'

# To create a tree structure usin materialised path pattern
gem 'ancestry', '~> 3.0.1'

# To act as a client
gem 'rest-client', '~> 2.0.2'
# Required by rest-client
gem 'http-accept'

# To read media files metadata
gem 'streamio-ffmpeg', '~> 3.0.2'

# To manage .zip files
gem 'rubyzip', '~> 1.2.1', require: 'zip'

# Monitor personal files in local environments
group :development_local, :staging_local, :production_local do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

#Monitor application in remote environments
group :staging_remote, :production_remote do
  gem 'newrelic_rpm'
end
